### ISSUE TITLE
Issue with icon

### ISSUE THREAD

**Issue by bdukes** [EngageSoftware/cantarus-polydeploy-client#2]
Error when publishing:
>Uploaded extension package is either missing an icon or the provided icon image does not comply with the required dimensions. Try again with a square icon with size 128 by 128 pixels or larger.

**Comment by mitchelsellers** [comment]
@bdukes It looks like it is correct, and I see the icon as included with the shared copy you gave me.

I do see  that in all of the examples it is included as images/... Not sure if they are expecting a folder?

**Comment by bdukes** [comment]
😢  77385a1 didn't help…

**Comment by mitchelsellers** [comment]
This might be silly....but have you tried without the /images folder being in the files node?

**Comment by bdukes** [comment]
![You're a wizard](https://media.riffsy.com/images/0f8588a031f9aaa157df4f519b65180e/tenor.gif)

https://marketplace.visualstudio.com/items?itemName=engage-software.cantarus-polydeploy-client

**Comment by mitchelsellers** [comment]
That's hilarious....hoping I get approved tomorrow for mine!
